### ISSUE TITLE
Is this package live?

### ISSUE THREAD

**Issue by clukewatson** [SebKrantz/dfms#15]
I happen to start looking into DFM estimation in R and saw this package, but I don't think the package is on CRAN and I did not see a "devtools::install_github("SebKrantz/DFM") in the read_me, so I was just wondering if the package is live currently (Sept 14, 2022). 

Thanks,
Luke

**Comment by SebKrantz** [comment]
Yes, the package works well and you can install it from GitHub. I am
planning to submit it for ROpenSci scientific software review before
sending it to CRAN, which may result in changes to the API. But you are
very welcome to use it and give feedback.
