### ISSUE TITLE
Question: how do I get in-sample fitted values on the original scale? 

### ISSUE THREAD

**Issue by apoorvalal** [SebKrantz/dfms#45]
I'm trying to use `DFM` to impute missing potential outcomes as proposed in a series of recent papers (notably Yiqing's gsynth [paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2584200), [package](https://yiqingxu.org/packages/gsynth/)). I was wondering if there was a way to use `fitted` or `predict` (or some other internal pieces in the `DFM` object) to construct predicted values for missing outcomes in the original dataset. 

My question is can I impute the 50 missing values on the original scale using one of the object methods? 
+ `predict` does out-of-sample predictions as far as I can tell [happy to be corrected; i passed a negative value equal to the number of rows in the original dataset but that gave me an error] 
+ `fitted` is missing everywhere the original data is missing
+ `DFM$X_imp` has stationary, scaled imputations. 

Here's an example

```r
library(gsynth); library(dfms)

# loads turnout data - State X Year dataset on turnout, treatment is same day registration
data(gsynth) 

df = turnout[, 1:4] %>% setDT

# %% # reshape to T X N matrix with state time series columns
Y0mat = dcast(year ~ abb, data = df, value.var = "turnout")[,-1]  |> as.matrix()
Wmat  = dcast(year ~ abb, data = df, value.var = "policy_edr")[,-1]  |> as.matrix()
# set outcomes in treated periods to missing
Y0mat = replace(Y0mat, as.logical(Wmat), NA)
# Y0mat has missing values in treated periods for each state
# %% fit model
fm = DFM(Y0mat, r = 3, p = 3)
Y0hat = fitted(fm)
# %%
sum(is.na(Y0mat)) # 50 - number of missing outcomes
sum(is.na(Y0hat)) # 50 - same as number of missing outcomes
sum(is.na(fm$X_imp)) # non missing, but scaled
```

**Comment by apoorvalal** [comment]
Perfect, that worked. Thanks a lot for the excellent package and prompt response!

**Comment by SebKrantz** [comment]
Thanks, yeah I'll leave it open and add it, but I just pushed a minor update to CRAN, so it might take a few weeks.
