### ISSUE TITLE
Unstandardize data forecasts

### ISSUE THREAD

**Issue by mjng93** [SebKrantz/dfms#55]
Absolutely love this package; incredibly useful and performant. Was wondering, since you are standardizing the variables as part of the DFM() function, it looks like the forecasts for those variables when using predict() show up as the standardized versions (as opposed to whatever stationary series were provided to the model). Is there a way to save the mu/sigma values used as part of standardization  so that you can convert the projections back into whatever data was provided as input to the DFM() function?

**Comment by SebKrantz** [comment]
Hi, thanks. So `predict.dfm` has an argument `standardized = TRUE`. Setting `standardized = FALSE` gives prediction on the original scale. The means and standard deviations used to unscale the data are attached as an attributes called `"stats"` to the `X_imp` element of the *dfm* object, created by calling `collapse::qsu()` on the input data `X` before imputation.

**Comment by mjng93** [comment]
Got it! Amazing. Thank you.
